on:
  push:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Download source
        uses: actions/checkout@v3
        with:
          repository: iv-org/invidious
      - name: Install libsqlite3 static build
        run: apk add sqlite-static
      - name: Fix containerization git permission weirdness
        run: git config --global --add safe.directory /__w/invidious-precompile/invidious-precompile
      - name: Build invidious
        run: make STATIC=1
      - name: Compress binary, config and locales
        run: tar -cJf invidious.x86_64.tar.xz invidious locales config
      - name: Display SHA256 sum for archive
        run: sha256sum invidious.x86_64.tar.xz
      - name: Check date for version number
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> "$GITHUB_ENV"
      - name: Publish invidious static build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "invidious.x86_64.tar.xz"
          tag: "v${{ env.date }}.{{ github.sha }}"
