on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:latest-alpine
    steps:
      - name: Download source
        uses: actions/checkout@v2
        with:
          repository: iv-org/invidious
      - name: Install libsqlite3 static build
        run: apk add sqlite-static
      - name: Fix containerization git permission weirdness
        run: git config --global --add safe.directory /__w/invidious-precompile/invidious-precompile
      - name: Build invidious
        run: make STATIC=1
      - name: Publish invidious static build
        uses: actions/upload-artifact@v3
        with:
          name: invidious.x86_64
          path: invidious
